
[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[override]]
  name = "google.golang.org/grpc"
  source = "https://github.com/grpc/grpc-go.git"
  version = "=1.7.5"

[[override]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[override]]
  name = "github.com/pingcap/kvproto"
  revision = "2cf2492c337c4d0281d8ead8686d47764f1df6c4"

[[override]]
  name = "github.com/pingcap/tipb"
  revision = "2d5073e5521a10f8db2adc0eaab2c46ca0a151d9"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  branch = "master"

[[constraint]]
  name = "github.com/pingcap/tidb"
  version="=v2.0.8"

[[constraint]]
  name = "github.com/deckarep/golang-set"
  version = "v1.7.1"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "v1.2.0"