package terror

import "errors"

// Error Info
var (
	ErrCommand         = errors.New("ERR command error")
	ErrCmdParams       = errors.New("ERR command params error")
	ErrCmdDisable      = errors.New("ERR command disable")
	ErrKeyEmpty        = errors.New("ERR key cannot be empty")
	ErrKeyOrFieldEmpty = errors.New("ERR key or field cannot be empty")
	ErrTypeNotMatch    = errors.New("ERR WRONGTYPE Operation against a key holding the wrong kind of value")
	ErrTypeTrans       = errors.New("ERR value is not an integer or out of range")
	ErrCmdInBatch      = errors.New("ERR some command in batch not supported")
	ErrCmdNumber       = errors.New("ERR command not enough in batch")
	ErrBackendType     = errors.New("ERR backend type error")
	ErrTypeAssertion   = errors.New("ERR interface type assertion failed")
	ErrOutOfIndex      = errors.New("ERR index out of range")
	ErrInvalidMeta     = errors.New("ERR invalid key meta")
	ErrUnknownType     = errors.New("ERR unknown response data type")
	ErrRunWithTxn      = errors.New("ERR run run with txn")
	ErrAuthNoNeed      = errors.New("ERR Client sent AUTH, but no password is set")
	ErrAuthFailed      = errors.New("ERR invalid password")
	ErrAuthRequired    = errors.New("NOAUTH Authentication required")
	ErrKeyBusy         = errors.New("BUSYKEY key is deleting, retry later")
	ErrNotInteger      = errors.New("ERR value is not an integer or out of range")
	ErrTxnFailed       = errors.New("ERR Txn execute failed")
	ErrKeyNotExist     = errors.New("ERR Key not exist")
	ErrKeyExist        = errors.New("ERR Key Exists")
	ErrKeyNotValid     = errors.New("ERR Key not valide")
	ErrIdentify        = errors.New("ERR Identify Type Error")
	ErrUnbuildKey      = errors.New("ERR unbuild key")
	ErrNsInvalied      = errors.New("ERR namespace invalied group.service")
	ErrNsExist         = errors.New("ERR namespace already exist")
	ErrNsNotExist      = errors.New("ERR namespace not exist")
)
